# Generated by Django 5.1.3 on 2024-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='Example C Code', max_length=100),
            preserve_default=False,
        ),
    ]
