# Generated by Django 5.1.3 on 2024-12-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lang_id',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
