# Generated by Django 5.1.3 on 2025-01-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_remove_lang_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='lexer_name',
            field=models.CharField(default='noneee', max_length=100),
            preserve_default=False,
        ),
    ]
